export const TOGGLE_CART_VISIBILITY = "TOGGLE_CART_VISIBILITY";
export const ADD_ITEM = "ADD_ITEM";
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART";
export const REMOVE_ITEM = "REMOVE_ITEM";
